//menu

const recipeExplain = [
    {
        id: 1,
        title: '돈치고기고기',
        text: '국내산 돼지고기로 만든 반달 돈까스, 닭다리살의 치킨 가라아게,소불고기, 제육볶음 등 각종 고기반찬과 따끈따끈한 쌀밥, 여기에 구수한 된장에 각종 야채와 두부를 넣어 감칠맛이 일품인 두부강된장 소스를 비벼먹으면 최상의 단짠단짠 조합 완성!',
    },
    {
        id: 2,
        title: '해바라기',
        text: '점보 사이즈의 통닭다리와 통새우 4마리를 통째로 담은 통새우카츠, 청정 호주산 소불고기에 햄버그스테이크까지 총 10찬으로 구성된 풍성함 가득 담은 프리미엄 도시락. 식사의 마지막 꽃을 장식할 디저트 꿀호떡을 잊지마세요',
    },
    {
        id: 3,
        title: '치킨마요',
        text: '한솥 대표 메뉴로 한 입 크기로 자른 슬라이스 치킨 가라아게를 한솥의 시그니처 마요드레싱과 덮밥소스 비벼 한 입 한 다음, 소스와 치킨의 느끼해지는 속을 깨끗하게 해줄 김치찌개 국물 한 숟가락이 주는 따뜻함에 속까지 든든해집니다.',
    },
    {
        id: 4,
        title: '나시고랭',
        text: '큼직한 닭고기와 스파이시한 풍미를 듬뿍 넣어 볶아 더 맛있게 돌아온 한솥의 나시고랭. 신메뉴로 소개한 순간부터 지금까지 계속해서 인기메뉴의 자리를 지키고 있는 나시고랭에 치킨을 추가하면 최고의 한끼 완성!',
    },
    {
        id: 5,
        title: '참치마요',
        text: '담백한 참치와 한솥의 시그니처 마요드레싱과 덮밥소스를 뿌려 비벼먹는 덮밥 또한 꿀맛이지만 소스 대신 부드러운 고기카레를 참치와 함께 덮밥이랑 비벼벅으면 새로운 별미가 탄생!',
    },
    {
        id: 6,
        title: '개나리',
        text: '소불고기, 새우후라이, 치킨 가라아게, 고등어 간장구이 고기와 새우, 닭, 생선 모든 반찬이 모인 한상 모임. 따뜻한 국물을 책임질 김치찌개를 추가하는 순간 마치 집에서 먹는 듯한 든든함을 느낄 수 있습니다.',
    },
    {
        id: 7,
        title: '불닭덮밥',
        text: '화끈한 매운 맛이 일품인 덮밥소스와 쫄깃한 닭갈비와 고소한 치킨마요네즈의 만남 매콤달달한 닭갈비에 부드러운 치킨마요네즈의 조합을 마지막엔 자연산 모짜렐라, 고다, 체다가 감싸줍니다.',
    },
    {
        id: 8,
        title: '돈까스도련님',
        text: '국내산 돼지고기로 만든 반달 돈까스, 소불고기, 제육볶음 닭다리살의 치킨 가라아게까지 다양한 고기반찬이 주는 느끼함을 시원하게 잡아 줄 수 있는 김치찌개 김치나베를 만들어 먹을 수 있는 든든한 한끼 레시피',
    },
];

const productNew = [
    {
        id: 1,
        group: '#카레',
        name: '스페셜 하이라이스',
        text: '일본식 커리 소스에 데미그라스 소스가 더해져 깊은 풍미를 가진 하이라이스 위에 부드럽고 바삭한 멘치카츠와 육즙 가득 토네이도 소세지가 구성된 스페셜 하이라이스',
        imgurl: 'images/content/menu/product/new0.png',
    },
    {
        id: 2,
        group: '#모둠',
        name: '송정식 떡갈비 Ⅱ',
        text: '고슬고슬 밥 위에 가득 얹힌 부드러운 송정식 떡갈비와 국내산 김치만두 튀김, 제육볶음까지 구성되어 푸짐하고 든든하게 한 끼를 즐길 수 있는 송정식 떡갈비 Ⅱ',
        imgurl: 'images/content/menu/product/new1.png',
    },
    {
        id: 3,
        group: '#찌개',
        name: '이남장 설렁탕',
        text: '50년 전통의 맛을 그대로 담은, 깊은 육수와 두툼한 고기가 들어간 이남장 설렁탕 with 깐 대파, 흑후추, 미니 깍두기',
        imgurl: 'images/content/menu/product/new2.png',
    },
    {
        id: 4,
        group: '#모둠',
        name: '제육돈까스 도련님',
        text: '한솥의 인기 메뉴 돈까스 도련님에 한국인의 소울푸드 매콤 달달 제육볶음을 더해 푸짐한 구성으로 업그레이드된 제육 돈까스 도련님',
        imgurl: 'images/content/menu/product/new3.png',
    },
    {
        id: 5,
        group: '#찌개',
        name: '사골 조랭이떡 만둣국',
        text: '푹 고은 소고기 사골 육수에 쫄깃한 조랭이떡과 속이 꽉 찬 고기만두, 김치만두, 송송 썬 대파와 얇게 썬 지단까지 푸짐하게 즐길 수 있는 사골 조랭이떡만둣국',
        imgurl: 'images/content/menu/product/new4.png',
    },
    {
        id: 6,
        group: '#마요',
        name: '메가치킨마요',
        text: '밥 370g + 치킨 150g *치킨마요의 치킨 2.5배 증량된 메가 사이즈의 치킨 가라아게와 한솥의 시그니처 마요드레싱과 덮밥소스를 뿌려 비벼먹는 덮밥 ',
        imgurl: 'images/content/menu/product/new5.png',
    },
];
const productPre = [
    {
        id: 1,
        group: '#프리미엄',
        name: '해바라기',
        text: '점보 사이즈의 통닭다리와 통새우 4마리를 통째로 담은 통새우카츠, 청정 호주산 소불고기에 햄버그스테이크까지 총 10찬으로 구성된 풍성함 가득 담은 프리미엄 도시락 with 타르타르 소스, 양식소스 *미니생수, 조미김 포함',
        imgurl: 'images/content/menu/product/premium0.png',
    },
    {
        id: 2,
        group: '#프리미엄',
        name: '매화',
        text: '소불고기, 제육볶음, 새우후라이, 고등어 간장구이 등 총 10가지 다양한 반찬으로 구성된 프리미엄 도시락 with 타르타르 소스 *미니생수, 조미김 포함',
        imgurl: 'images/content/menu/product/premium1.png',
    },
    {
        id: 3,
        group: '#프리미엄',
        name: '진달래',
        text: '햄버그스테이크, 반달 돈까스, 새우후라이, 치킨 가라아게, 제육볶음이 포함된 한솥 TOP 5 메뉴의 푸짐한 프리미엄 도시락 with 양식소스 *미니생수, 조미김 포함',
        imgurl: 'images/content/menu/product/premium2.png',
    },
    {
        id: 4,
        group: '#프리미엄',
        name: '개나리',
        text: '소불고기, 새우후라이, 치킨 가라아게, 고등어 간장구이 등 누구나 좋아하는 반찬들로 구성된 프리미엄 도시락 with 타르타르 소스 *미니생수, 조미김 포함',
        imgurl: 'images/content/menu/product/premium3.png',
    },
    {
        id: 5,
        group: '#프리미엄',
        name: '무궁화',
        text: '닭다리살 치킨 가라아게와 매콤달콤한 부드러운 식감의 제육볶음의 치킨제육에 치킨과 제육볶음의 양이 2.5배 증량된 도시락 (밥 300g)',
        imgurl: 'images/content/menu/product/premium4.png',
    },
    {
        id: 6,
        group: '#프리미엄',
        name: '동백',
        text: '반달 돈까스, 치킨 가라아게, 스팸 등 한솥 인기 반찬 도시락과 깊고 진한 김치 부대찌개 조합의 정식 메뉴 with 양식소스 *미니생수, 조미김 포함',
        imgurl: 'images/content/menu/product/premium5.png',
    },
];
const productSquare = [
    {
        id: 1,
        group: '#모둠',
        name: '돈까스도련님',
        text: '반달 돈까스, 햄버그스테이크, 치킨 가라아게 등 실속 반찬들로만 구성된 한솥 대표 BEST 가성비 도시락 with 양식소스',
        imgurl: 'images/content/menu/product/square0.png',
    },
    {
        id: 2,
        group: '#모둠',
        name: '숯불직화구이',
        text: '석쇠에 구워 숯불향이 가득한 직화구이에 매콤한 풍미를 더한 라유소스와 다양한 밑반찬으로 구성된 정식 도시락 with 라유소스',
        imgurl: 'images/content/menu/product/square1.png',
    },
    {
        id: 3,
        group: '#모둠',
        name: '메가치킨제육',
        text: '닭다리살 치킨 가라아게와 매콤달콤한 부드러운 식감의 제육볶음의 치킨제육에 치킨과 제육볶음의 양이 2.5배 증량된 도시락 (밥 300g)',
        imgurl: 'images/content/menu/product/square2.png',
    },
    {
        id: 4,
        group: '#모둠',
        name: '돈치스팸',
        text: '국내산 돼지고기로 만든 반달 돈까스, 치킨 가라아게, 스팸 등 한솥 인기 반찬으로 구성된 든든한 도시락 with 양식소스',
        imgurl: 'images/content/menu/product/square3.png',
    },
    {
        id: 5,
        group: '#모둠',
        name: '제육볶음',
        text: '남녀노소 누구나 좋아하는 매콤달콤한 부드러운 식감의 제육볶음 가득 담아 다양한 밑반찬과 함께 즐기기 좋은 도시락',
        imgurl: 'images/content/menu/product/square4.png',
    },
    {
        id: 6,
        group: '#모둠',
        name: '떡갈비 도련님',
        text: '국내산 돼지 갈비살과 호주산 쇠고기를 다져만든 촉촉하고 쫄깃한 식감의 빅 사이즈 ‘송정식 떡갈비’와 제육볶음, 오색전, 미니 메밀전병 등 총 8종 반찬을 함께 즐길 수 있는 푸짐한 한 상 차림의 도시락',
        imgurl: 'images/content/menu/product/square5.png',
    },
];
const productBowl = [
    {
        id: 1,
        group: '#마요',
        name: '치킨마요',
        text: '2003년 최초 개발된 한솥 대표 메뉴로 한 입 크기로 자른 슬라이스 치킨 가라아게를 한솥의 시그니처 마요드레싱과 덮밥소스를 뿌려 비벼먹는 덮밥 with 커플소스, 조미김 (밥 230g + 치킨 60g)',
        imgurl: 'images/content/menu/product/bowl0.png',
    },
    {
        id: 2,
        group: '#마요',
        name: '참치마요',
        text: '담백한 참치와 한솥의 시그니처 마요드레싱과 덮밥소스를 뿌려 비벼먹는 덮밥 with 커플소스, 조미김',
        imgurl: 'images/content/menu/product/bowl1.png',
    },
    {
        id: 3,
        group: '#비빔밥',
        name: '아보카도 명란 비빔밥',
        text: '영양가득 슈퍼푸드 아보카도에 단짠단짠 소불고기 토핑으로 고소한 명란마요, 상큼한 레몬간장소스와 함께 비벼 먹을 수 있는 비빔밥',
        imgurl: 'images/content/menu/product/bowl2.png',
    },
    {
        id: 4,
        group: '#볶음밥',
        name: '잡채볶음밥',
        text: '가마솥 직화 방식으로 지어 고슬고슬한 식감을 살린 밥에 쫄깃한 당면, 부드러운 닭다리살과 양배추, 청피망, 당근, 대파 등 4가지 채소를 듬뿍 넣어 직화로 볶은 잡채볶음밥',
        imgurl: 'images/content/menu/product/bowl3.png',
    },
    {
        id: 5,
        group: '#볶음밥',
        name: '나시고랭',
        text: 'CNN에서 선정한 세계에서 가장 맛있는 음식 2위! 큼직한 닭고기와 스파이시한 풍미를 듬뿍 넣어 볶아 더 맛있게 돌아온 한솥 나시고랭',
        imgurl: 'images/content/menu/product/bowl4.png',
    },
    {
        id: 5,
        group: '#볶음밥',
        name: '치킨마요 정식',
        text: '한솥 대표 인기 메뉴 치킨마요와 깊고 진한 김치 부대찌개로 구성된 정식 메뉴 with 커플소스, 조미김',
        imgurl: 'images/content/menu/product/bowl5.png',
    },
];
const productSide = [
    {
        id: 1,
        group: '#반찬',
        name: '3종 미니반찬A',
        text: '매콤한 무말랭이, 콘샐러드, 새콤한 해초무침 3가지로 알차게 구성된 인기 반찬 메뉴',
        imgurl: 'images/content/menu/product/side0.png',
    },
    {
        id: 2,
        group: '#반찬',
        name: '3종 미니반찬B',
        text: '고소한 아몬드멸치볶음, 마카로니샐러드, 짭쪼름한 오징어젓갈 3가지로 실속있게 구성된 인기 반찬 메뉴',
        imgurl: 'images/content/menu/product/side1.png',
    },
    {
        id: 3,
        group: '#반찬',
        name: '반찬 묵은지김치찌개',
        text: '진한 사골 육수에 국내산 김치와 부드러운 돼지 앞다리살을 뭉근하게 끓여 진한 국물맛의 칼칼함이 특징인 한솥 묵은지 김치찌개',
        imgurl: 'images/content/menu/product/side2.png',
    },
    {
        id: 4,
        group: '#반찬',
        name: '반찬 카레',
        text: '20년동안 인기를 이어온 한솥만의 오리지널 특제 카레',
        imgurl: 'images/content/menu/product/side3.png',
    },
    {
        id: 5,
        group: '#간식안주',
        name: '통현미 닭강정',
        text: '한솥에서 1년이 넘는 기간동안 연구 개발한 한솥의 베스트 인기 간식 메뉴로 매콤달콤 소스에 현미 크런치 토핑을 더한 순살 닭강정',
        imgurl: 'images/content/menu/product/side4.png',
    },
    {
        id: 6,
        group: '#간식',
        name: '리얼꿀 미니호떡',
        text: '부드럽고 쫀득한 식감과 꿀앙금, 견과류가 들어있어 달콤하고 고소한 맛의 미니호떡(3개)',
        imgurl: 'images/content/menu/product/side5.png',
    },
];
const productKey = [
    {
        id: 1,
        group: '#한솥베스트셀러',
        name: '스팸김치볶음밥',
        text: '베이컨, 양파, 대파, 홍피망을 넣어 불 맛을 살린 볶음밥과 짭쪼름한 스팸과 계란후라이로 감칠맛을 살린 스팸 철판볶음밥 wIth 조미김',
        imgurl: 'images/content/menu/product/key0.png',
    },
    {
        id: 2,
        group: '#따끈한 집밥이 생각날 때',
        name: '제육 김치찌개 정식',
        text: '매콤달콤한 제육볶음, 계란후라이, 진한 국물맛의 칼칼한 묵은지 김치찌개의 완벽한 조합으로 든든한 한 상 차림의 정식 메뉴 *미니생수, 조미김 포함',
        imgurl: 'images/content/menu/product/key1.png',
    },
    {
        id: 3,
        group: '#화끈하게 스트레스 날리기',
        name: '핫치즈 닭갈비덮밥',
        text: '화끈한 매운 맛이 일품인 닭갈비 덮밥소스에 자연산 100% 3종치즈(모짜렐라, 고다, 체다)를 듬뿍 올린 핫 치즈 닭갈비덮밥',
        imgurl: 'images/content/menu/product/key2.png',
    },
    {
        id: 4,
        group: '#건강을 위해',
        name: '소불고기 비빔밥',
        text: '소불고기와 당근, 치커리, 계란지단채, 취나물, 버섯, 김가루 등 다양한 채소를 듬뿍 담아 계란후라이와 함께 매콤달콤한 한솥 특제 감초고추장과 비벼먹는 감칠맛이 특징인 비빔밥 with 감초볶음고추장소스, 참기름',
        imgurl: 'images/content/menu/product/key3.png',
    },
    {
        id: 5,
        group: '#반찬만 필요할 때',
        name: '반찬 돈까스도련님',
        text: '국내산 돼지고기의 등심으로 만든 반달 돈까스, 부드러운 햄버그스테이크, 짭조름한 치킨 가라아게가 들어있는 특별 반찬',
        imgurl: 'images/content/menu/product/key4.png',
    },
    {
        id: 6,
        group: '#추천 단체도시락',
        name: '새치고기고기',
        text: '햄버그스테이크, 새우후라이, 치킨 가라아게, 소불고기 등 한솥 대표 반찬들로 구성된 스테디셀러 도시락 with 타르타르 소스, 조미김',
        imgurl: 'images/content/menu/product/key5.png',
    },
];

//  //.menu

// store

const storePlace = [
    {
        id: 1,
        store: '인하대후문점',
        phone: '032-438-7723',
        location: '인천광역시 남구 용현4동 198-32',
        open: '10:00~20:00',
    },
    {
        id: 2,
        store: '주안역점',
        phone: '032-868-7573',
        location: '인천광역시 남구 주안로90번길 4',
        open: '7:00~22:00',
    },
    {
        id: 3,
        store: '부평역점',
        phone: '032-501-0365',
        location: '인천광역시 부평구 부평1동 185-58',
        open: '8:00~21:00',
    },
    {
        id: 4,
        store: '송도컨벤시아점',
        phone: '032-835-6954',
        location: '인천광역시 연수구 송도동 4-1 송도더샾퍼스트 제3디(지동)동 1층 67호',
        open: '8:00~20:00',
    },
    {
        id: 5,
        store: '삼산월드체육관점',
        phone: '032-266-5400',
        location: '인천광역시 부평구 삼산동 462-3',
        open: '9:00~21:00',
    },
    {
        id: 6,
        store: '건지사거리점',
        phone: '032-719-8200',
        location: '인천광역시 서구 가좌동 122-8 107호2',
        open: '8:00~21:00',
    },
    {
        id: 7,
        store: '인천만수3지구점',
        phone: '032-467-1117',
        location: '인천광역시 남동구 만수동 1019-4 에메랄드B 101',
        open: '8:00~21:00',
    },
    {
        id: 8,
        store: '연수동춘점',
        phone: '032-816-1040',
        location: '인천광역시 남구 용현4동 198-32',
        open: '8:00~21:00',
    },
    {
        id: 9,
        store: '산곡고앞점',
        phone: '032-518-6688',
        location: '인천광역시 부평구 청천동 236-17',
        open: '9:00~21:00',
    },
    {
        id: 10,
        store: '효성두산아파트앞점',
        phone: '032-545-4343',
        location: '인천광역시 계양구 효성동 51-10번지',
        open: '8:00~21:00',
    },
    {
        id: 11,
        store: '인천검단사거리점',
        phone: '032-567-3435',
        location: '인천광역시 서구 완정로 185 1층 103호(왕길동)',
        open: '8:00~21:00',
    },
    {
        id: 12,
        store: '공항신도시점',
        phone: '032-746-0051',
        location: '인천광역시 중구 운서동 2793-1',
        open: '8:00~21:00',
    },
    {
        id: 13,
        store: '용산삼각지점',
        phone: '02-796-0357',
        location: '서울특별시 용산구 한강로 2가 115-1 전자빌딩 103호',
        open: '10:00~20:00',
    },
    {
        id: 14,
        store: '논현힐탑점',
        phone: '02-514-1112',
        location: '서울시 강남구 논현로 120 길 14, 1층 102호',
        open: '7:00~22:00',
    },
    {
        id: 15,
        store: '신도림테크노마트점',
        phone: '02-2111-1800',
        location: '서울특별시 구로구 구로동 3-25 신도림테크노마트 지하1층 27호',
        open: '8:00~21:00',
    },
    {
        id: 16,
        store: '성산초교사거리점',
        phone: '02-336-7469',
        location: '서울특별시 마포구 망원1동 386-3',
        open: '8:00~20:00',
    },
    {
        id: 17,
        store: '노량진6번출구점',
        phone: '02-823-2610',
        location: '서울특별시 동작구 노량진동 41-5 건설상가 106호',
        open: '9:00~21:00',
    },
    {
        id: 18,
        store: '구로개봉점',
        phone: '02-2688-2414',
        location: '서울시 구로구 개봉로 17길 8 (개봉동)',
        open: '8:00~21:00',
    },
    {
        id: 19,
        store: '관악난곡점',
        phone: '02-6448-7537',
        location: '서울시 관악구 신림동 704-7번지',
        open: '8:00~21:00',
    },
    {
        id: 20,
        store: '개포4동점',
        phone: '02-572-9633',
        location: '서울특별시 강남구 개포동 1218-30',
        open: '8:00~21:00',
    },
    {
        id: 21,
        store: '송파문정엠스테이트점',
        phone: '02-401-6464',
        location: '서울시 송파구 문정동 643-1 엠스테이트 C동 109호',
        open: '9:00~21:00',
    },
    {
        id: 22,
        store: '건대후문점',
        phone: '02-456-8889',
        location: '서울특별시 광진구 화양동 507-2',
        open: '8:00~21:00',
    },
    {
        id: 23,
        store: '신당점',
        phone: '02-2233-4653',
        location: '서울특별시 중구 신당4동 340-77',
        open: '8:00~21:00',
    },
    {
        id: 24,
        store: '서울과학기술대앞점',
        phone: '02-949-5506',
        location: '서울특별시 노원구 공릉동 440-16 도곡빌딩1층',
        open: '8:00~21:00',
    },
];

const storePlaceIncheon = [
    {
        id: 1,
        store: '인하대후문점',
        phone: '032-438-7723',
        location: '인천광역시 남구 용현4동 198-32',
        open: '10:00~20:00',
    },
    {
        id: 2,
        store: '주안역점',
        phone: '032-868-7573',
        location: '인천광역시 남구 주안로90번길 4',
        open: '7:00~22:00',
    },
    {
        id: 3,
        store: '부평역점',
        phone: '032-501-0365',
        location: '인천광역시 부평구 부평1동 185-58',
        open: '8:00~21:00',
    },
    {
        id: 4,
        store: '송도컨벤시아점',
        phone: '032-835-6954',
        location: '인천광역시 연수구 송도동 4-1 송도더샾퍼스트 제3디(지동)동 1층 67호',
        open: '8:00~20:00',
    },
    {
        id: 5,
        store: '삼산월드체육관점',
        phone: '032-266-5400',
        location: '인천광역시 부평구 삼산동 462-3',
        open: '9:00~21:00',
    },
    {
        id: 6,
        store: '건지사거리점',
        phone: '032-719-8200',
        location: '인천광역시 서구 가좌동 122-8 107호2',
        open: '8:00~21:00',
    },
    {
        id: 7,
        store: '인천만수3지구점',
        phone: '032-467-1117',
        location: '인천광역시 남동구 만수동 1019-4 에메랄드B 101',
        open: '8:00~21:00',
    },
    {
        id: 8,
        store: '연수동춘점',
        phone: '032-816-1040',
        location: '인천광역시 남구 용현4동 198-32',
        open: '8:00~21:00',
    },
    {
        id: 9,
        store: '산곡고앞점',
        phone: '032-518-6688',
        location: '인천광역시 부평구 청천동 236-17',
        open: '9:00~21:00',
    },
    {
        id: 10,
        store: '효성두산아파트앞점',
        phone: '032-545-4343',
        location: '인천광역시 계양구 효성동 51-10번지',
        open: '8:00~21:00',
    },
    {
        id: 11,
        store: '인천검단사거리점',
        phone: '032-567-3435',
        location: '인천광역시 서구 완정로 185 1층 103호(왕길동)',
        open: '8:00~21:00',
    },
    {
        id: 12,
        store: '공항신도시점',
        phone: '032-746-0051',
        location: '인천광역시 중구 운서동 2793-1',
        open: '8:00~21:00',
    },
];
const storePlaceSeoul = [
    {
        id: 1,
        store: '용산삼각지점',
        phone: '02-796-0357',
        location: '서울특별시 용산구 한강로 2가 115-1 전자빌딩 103호',
        open: '10:00~20:00',
    },
    {
        id: 2,
        store: '논현힐탑점',
        phone: '02-514-1112',
        location: '서울시 강남구 논현로 120 길 14, 1층 102호',
        open: '7:00~22:00',
    },
    {
        id: 3,
        store: '신도림테크노마트점',
        phone: '02-2111-1800',
        location: '서울특별시 구로구 구로동 3-25 신도림테크노마트 지하1층 27호',
        open: '8:00~21:00',
    },
    {
        id: 4,
        store: '성산초교사거리점',
        phone: '02-336-7469',
        location: '서울특별시 마포구 망원1동 386-3',
        open: '8:00~20:00',
    },
    {
        id: 5,
        store: '노량진6번출구점',
        phone: '02-823-2610',
        location: '서울특별시 동작구 노량진동 41-5 건설상가 106호',
        open: '9:00~21:00',
    },
    {
        id: 6,
        store: '구로개봉점',
        phone: '02-2688-2414',
        location: '서울시 구로구 개봉로 17길 8 (개봉동)',
        open: '8:00~21:00',
    },
    {
        id: 7,
        store: '관악난곡점',
        phone: '02-6448-7537',
        location: '서울시 관악구 신림동 704-7번지',
        open: '8:00~21:00',
    },
    {
        id: 8,
        store: '개포4동점',
        phone: '02-572-9633',
        location: '서울특별시 강남구 개포동 1218-30',
        open: '8:00~21:00',
    },
    {
        id: 9,
        store: '송파문정엠스테이트점',
        phone: '02-401-6464',
        location: '서울시 송파구 문정동 643-1 엠스테이트 C동 109호',
        open: '9:00~21:00',
    },
    {
        id: 10,
        store: '건대후문점',
        phone: '02-456-8889',
        location: '서울특별시 광진구 화양동 507-2',
        open: '8:00~21:00',
    },
    {
        id: 11,
        store: '신당점',
        phone: '02-2233-4653',
        location: '서울특별시 중구 신당4동 340-77',
        open: '8:00~21:00',
    },
    {
        id: 12,
        store: '서울과학기술대앞점',
        phone: '02-949-5506',
        location: '서울특별시 노원구 공릉동 440-16 도곡빌딩1층',
        open: '8:00~21:00',
    },
];
const storeNew = [
    {
        id: 1,
        store: '대전스마트시티점',
        phone: '042-864-4919',
        location:
            '대전광역시 유성구 엑스포로123번길 34, 127호(도룡동, 도룡코아루스마트리치오피스텔)',
    },
    {
        id: 2,
        store: '미사역9번출구점',
        phone: '031-792-9992',
        location: '경기도 하남시 망월동 1116, 108호',
    },
    {
        id: 3,
        store: '부산망미점',
        phone: '051-753-5454',
        location: '부산 수영구 과정로73 하영메디칼빌딩1층',
    },
    {
        id: 4,
        store: '마곡나루역점',
        phone: '02-6958-5503',
        location: '서울 강서구 마곡중앙5로1길 21 102호',
    },
];
// //  .store
export {
    recipeExplain,
    productNew,
    productKey,
    productSide,
    productSquare,
    productBowl,
    productPre,
    storePlaceIncheon,
    storePlace,
    storePlaceSeoul,
    storeNew,
};

// hansot

export let seoulArr = [
    '군/구 선택',
    '강남구',
    '강동구',
    '강북구',
    '강서구',
    '관악구',
    '광진구',
    '구로구',
    '금천구',
    '노원구',
    '도봉구',
    '동대문구',
    '동작구',
    '마포구',
    '서대문구',
    '서초구',
    '성동구',
    '성북구',
    '송파구',
    '양천구',
    '영등포구',
    '용산구',
    '은평구',
    '종로구',
    '중구',
    '중랑구',
];

export let incheonArr = [
    '군/구 선택',
    '계양구',
    '남구',
    '남동구',
    '동구',
    '부평구',
    '서구',
    '연수구',
    '중구',
    '강화군',
    '옹진군',
];

export let daejeonArr = ['군/구 선택', '대덕구', '동구', '서구', '유성구', '중구'];
export let gwangjuArr = ['군/구 선택', '광산구', '남구', '동구', '북구', '서구'];
export let daeguArr = [
    '군/구 선택',
    '남구',
    '달서구',
    '동구',
    '북구',
    '서구',
    '수성구',
    '중구',
    '달성군',
];

export let ulsanArr = ['군/구 선택', '남구', '동구', '북구', '중구', '울주군'];

export let busanArr = [
    '군/구 선택',
    '강서구',
    '금정구',
    '남구',
    '동구',
    '동래구',
    '부산진구',
    '북구',
    '사상구',
    '사하구',
    '서구',
    '수영구',
    '연제구',
    '영도구',
    '중구',
    '해운대구',
    '기장군',
];

export let gyeonggiArr = [
    '군/구 선택',
    '고양시',
    '과천시',
    '광명시',
    '광주시',
    '구리시',
    '군포시',
    '김포시',
    '남양주시',
    '동두천시',
    '부천시',
    '성남시',
    '수원시',
    '시흥시',
    '안산시',
    '안성시',
    '안양시',
    '양주시',
    '오산시',
    '용인시',
    '의왕시',
    '의정부시',
    '이천시',
    '파주시',
    '평택시',
    '포천시',
    '하남시',
    '화성시',
    '가평군',
    '양평군',
    '여주군',
    '연천군',
];

export let gwangwonArr = [
    '군/구 선택',
    '강릉시',
    '동해시',
    '삼척시',
    '속초시',
    '원주시',
    '춘천시',
    '태백시',
    '고성군',
    '양구군',
    '양양군',
    '영월군',
    '인제군',
    '정선군',
    '철원군',
    '평창군',
    '홍천군',
    '화천군',
    '횡성군',
];

export let northCungcheongArr = [
    '군/구 선택',
    '제천시',
    '청주시',
    '충주시',
    '괴산군',
    '단양군',
    '보은군',
    '영동군',
    '옥천군',
    '음성군',
    '증평군',
    '진천군',
    '청원군',
];

export let southCungcheongArr = [
    '군/구 선택',
    '계룡시',
    '공주시',
    '논산시',
    '보령시',
    '서산시',
    '아산시',
    '천안시',
    '금산군',
    '당진군',
    '부여군',
    '서천군',
    '연기군',
    '예산군',
    '청양군',
    '태안군',
    '홍성군',
];

export let northJeonraArr = [
    '군/구 선택',
    '군산시',
    '김제시',
    '남원시',
    '익산시',
    '전주시',
    '정읍시',
    '고창군',
    '무주군',
    '부안군',
    '순창군',
    '완주군',
    '임실군',
    '장수군',
    '진안군',
];
export let southJeonraArr = [
    '군/구 선택',
    '광양시',
    '나주시',
    '목포시',
    '순천시',
    '여수시',
    '강진군',
    '고흥군',
    '곡성군',
    '구례군',
    '담양군',
    '무안군',
    '보성군',
    '신안군',
    '영광군',
    '영암군',
    '완도군',
    '장성군',
    '장흥군',
    '진도군',
    '함평군',
    '해남군',
    '화순군',
];
export let northGyeongsangArr = [
    '군/구 선택',
    '경산시',
    '경주시',
    '구미시',
    '김천시',
    '문경시',
    '상주시',
    '안동시',
    '영주시',
    '영천시',
    '포항시',
    '고령군',
    '군위군',
    '봉화군',
    '성주군',
    '영덕군',
    '영양군',
    '예천군',
    '울릉군',
    '울진군',
    '의성군',
    '청도군',
    '청송군',
    '칠곡군',
];
export let southGyeongsangArr = [
    '군/구 선택',
    '거제시',
    '김해시',
    '마산시',
    '밀양시',
    '사천시',
    '양산시',
    '진주시',
    '진해시',
    '창원시',
    '통영시',
    '거창군',
    '고성군',
    '남해군',
    '산청군',
    '의령군',
    '창녕군',
    '하동군',
    '함안군',
    '함양군',
    '합천군',
];
export let jejuArr = ['군/구 선택', '서귀포시', '제주시', '남제주군', '북제주군'];

export const faqPosts = [
    {
        id: 1,
        sort: '이용방법',
        title: '주문앱으로 배달 가능한가요?',
        icon: 'images/content/frequently_asked/arrow_right.png',
    },
    {
        id: 2,
        sort: '계정',
        title: '회원가입을 하면 어떤 장점이 있나요?',
        icon: 'images/content/frequently_asked/arrow_right.png',
    },
    {
        id: 3,
        sort: '이용방법',
        title: '비회원으로 주문이 가능한가요?',
        icon: 'images/content/frequently_asked/arrow_right.png',
    },
    {
        id: 4,
        sort: '점포',
        title: '제 주변에 있는 한솥 점포를 어떻게 찾을 수 있나요?',
        icon: 'images/content/frequently_asked/arrow_right.png',
    },
    {
        id: 5,
        sort: '점포',
        title: '점포 영업시간은 어디서 확인 할 수 있나요?',
        icon: 'images/content/frequently_asked/arrow_right.png',
    },
    {
        id: 6,
        sort: '이용방법',
        title: '주문앱의 혜택이 무엇인가요?',
        icon: 'images/content/frequently_asked/arrow_right.png',
    },
    {
        id: 7,
        sort: '계정',
        title: '회원정보는 어떻게 업데이트 할 수 있나요?',
        icon: 'images/content/frequently_asked/arrow_right.png',
    },
    {
        id: 8,
        sort: '이용방법',
        title: '주문앱으로 결제 방법은 무엇이 있나요?',
        icon: 'images/content/frequently_asked/arrow_right.png',
    },
    {
        id: 9,
        sort: '계정',
        title: '로그아웃은 어떻게 할 수 있나요?',
        icon: 'images/content/frequently_asked/arrow_right.png',
    },
    {
        id: 10,
        sort: '이용방법',
        title: '주문앱으로 주문하면 언제 음식이 만들어지나요?',
        icon: 'images/content/frequently_asked/arrow_right.png',
    },
    {
        id: 11,
        sort: '계정',
        title: '주문내역은 어디서 확인 할 수 있나요?',
        icon: 'images/content/frequently_asked/arrow_right.png',
    },
    {
        id: 12,
        sort: '이용방법',
        title: '주문앱으로 주문 수량 제한이 있나요?',
        icon: 'images/content/frequently_asked/arrow_right.png',
    },
    {
        id: 13,
        sort: '계정',
        title: '비밀번호를 잊었습니다. 어떻게 해야 되나요?',
        icon: 'images/content/frequently_asked/arrow_right.png',
    },
    {
        id: 14,
        sort: '이용방법',
        title: '주문앱으로 주문한 음식은 언제 픽업 하면 되나요?',
        icon: 'images/content/frequently_asked/arrow_right.png',
    },
    {
        id: 15,
        sort: '이용방법',
        title: '주문 넣은 후 주문 수정 가능한가요?',
        icon: 'images/content/frequently_asked/arrow_right.png',
    },
    {
        id: 16,
        sort: '이용방법',
        title: '주문 취소는 어떻게 하나요?',
        icon: 'images/content/frequently_asked/arrow_right.png',
    },
    {
        id: 17,
        sort: '이용방법',
        title: '주문앱으로 단체주문은 어떻게 하나요?',
        icon: 'images/content/frequently_asked/arrow_right.png',
    },
    {
        id: 18,
        sort: '이용방법',
        title: '주문앱을 이용한 주문은 몇시 부터 몇시 까지 가능하나요?',
        icon: 'images/content/frequently_asked/arrow_right.png',
    },
    {
        id: 19,
        sort: '이용방법',
        title: '점포에 도착 후 도시락은 어떻게 픽업 하나요?',
        icon: 'images/content/frequently_asked/arrow_right.png',
    },
    {
        id: 20,
        sort: '이용방법',
        title: '주문앱으로 후불 가능한가요?',
        icon: 'images/content/frequently_asked/arrow_right.png',
    },
    {
        id: 21,
        sort: '이용방법',
        title: '비회원 주문 내역은 어디서 확인하나요?',
        icon: 'images/content/frequently_asked/arrow_right.png',
    },
    {
        id: 22,
        sort: '이용방법',
        title: '결제를 완료했는데 메뉴를 추가하고 싶어요.',
        icon: 'images/content/frequently_asked/arrow_right.png',
    },
    {
        id: 23,
        sort: '이용방법',
        title: '픽업 시간 알림이 따로 있나요?',
        icon: 'images/content/frequently_asked/arrow_right.png',
    },
    {
        id: 24,
        sort: '이용방법',
        title: '점포에 도착 후 도시락은 어떻게 픽업 하나요?',
        icon: 'images/content/frequently_asked/arrow_right.png',
    },
    {
        id: 25,
        sort: '결제',
        title: '결제 PIN번호를 잊어버렸습니다. 어떻게 해야 되나요?',
        icon: 'images/content/frequently_asked/arrow_right.png',
    },
    {
        id: 26,
        sort: '결제',
        title: '왜 와이파이로는 결제가 되지않나요?',
        icon: 'images/content/frequently_asked/arrow_right.png',
    },
    {
        id: 27,
        sort: '결제',
        title: '결제가 이중으로 되었어요. 어떻게 해야 하나요?',
        icon: 'images/content/frequently_asked/arrow_right.png',
    },
    {
        id: 28,
        sort: '계정',
        title: '회원정보는 어떻게 업데이트 할 수 있나요?',
        icon: 'images/content/frequently_asked/arrow_right.png',
    },
    {
        id: 29,
        sort: '계정',
        title: '가입시 아이디를 잘못해서 바꾸고 싶은데 변경할 수 있나요?',
        icon: 'images/content/frequently_asked/arrow_right.png',
    },
    {
        id: 30,
        sort: '계정',
        title: '회원 탈퇴 후 재가입을 할 수 있나요?',
        icon: 'images/content/frequently_asked/arrow_right.png',
    },
    {
        id: 31,
        sort: '쿠폰',
        title: '모바일 시식권을 쿠폰으로 사용할 수 있나요?',
        icon: 'images/content/frequently_asked/arrow_right.png',
    },
];

export const newsContent = [
    {
        id: 1,
        link: 'https://www.thefirstmedia.net/news/articleView.html?idxno=127481',
        date: '2024-04-42',
        image: 'images/content/news/01.jpg',
        name: 'THE FIRST',
        title: '한솥, ‘2023 사랑나눔 사회공헌 대상’ ESG 경영 부문 경제부총리상 수상',
        text: '한솥은 19일 제10회 ‘2023 사랑나눔 사회공헌 대상’ ESG 경영 부문에서 경제부총리 겸 기획재정부 장관상을 수상했다고 밝혔다. 사랑나눔 사회공헌 대상은 조선비즈가 주최하고 경제부총리 겸 기획재정부와 교육부, 과학기술 정보통신부, 행정안전부, 농림축산식품부 등 총 14개 부처가 후원하는 시상식이다. 사회적 책임을 다하는 기업들의 사례를 발굴, 사회공헌 문화 확산 및 새로운 경영 모델 제시를 위해 제정됐다. 이 상은 활발한 사회공헌 활동으로 국민에게 존경받는 기업에게 주어진다. 이번 시상에서 한솥은 ▲경영자의 사회공헌 철학 ▲사회공헌 전략 및 장단기 계획 ▲사회공헌 활동을 위한 조직체계 ▲사회공헌 활동 내용 ▲사회공헌 활동에 대한 자체 평가 ▲사회공헌 활동에 대한 외부기관 및 관련단체의 평가까지, 까다로운 절차에서 가장 높은 평가를 받아 ESG 경영 부문 경제부총리 겸 기획재정부 장관상을 수상하게 됐다.',
        icon: 'images/content/news/news_icons.png',
    },
    {
        id: 2,
        link: 'https://www.news1.kr/articles/5367492',
        date: '2024-04-42',
        image: 'images/content/news/02.jpg',
        name: '뉴스1',
        title: "한솥도시락, '2024 대한민국 명품브랜드 대상' 9년 연속 수상",
        text: "한솥도시락은 지난달 27일 열린 '2024 대한민국 명품브랜드 대상' 시상식에서 도시락 프랜차이즈 부문 9년 연속 수상을 했다고 29일 밝혔다. 대한민국 명품브랜드 대상 수상 브랜드와 기업은 '명품브랜드 고객평가(KPB-CRI)'와 '명품브랜드 특성 평가(KPB-CV)'를 거쳐 점수를 합산해 최종 선정된다. 한국리서치가 조사하는 명품브랜드 고객평가에서는 만 20~59세 남녀를 대상으로 인터뷰를 통해 진행된다. 명품브랜드 특성 평가에서는 학계·산업계 전문가 다수가 '기업 경영 실적'을 평가할 수 있는 △재무성과 지표와 '명품브랜드로서의 특성'을 평가할 수 있는 △전략적 가치 △명품브랜드 가치 △명품브랜드 관리 등 세부 평가 지표에 따라 점수를 산출한다. 한솥도시락 측은 지난 30여년간 꾸준히 이어온 ESG 경영을 통해 국내 소비 수준 및 품질 향상에 기여한 점을 인정받은 것이라고 설명했다.",
        icon: 'images/content/news/news_icons.png',
    },
    {
        id: 3,
        link: 'https://dailian.co.kr/news/view/1335730/?sc=Naver',
        date: '2024-03-08',
        image: 'images/content/news/03.jpg',
        name: '데일리안',
        title: '한솥도시락, 가성비 K-소울푸드 신메뉴 2종 출시상',
        text: '국내 도시락 프랜차이즈 한솥도시락이 한국인의 소울푸드를 활용한 가성비 높은 신메뉴를 출시하며, 고물가 속에서 외식 비용에 부담을 느끼고 있는 소비자들에게 주목을 받고 있다. 한솥도시락은 3월 기간한정으로 ‘제육돈까스 도련님’과 ‘김피탕’ 메뉴를 출시했다. 두 메뉴 모두 한국인들에게 대표적으로 사랑받는 음식을 메인으로 구성하고 가성비 넘치는 가격까지 더했다. 먼저 ‘제육돈까스 도련님’은 한국인 대표 선호 음식 2가지인 제육볶음과 돈까스를 메인으로 구성해 누구나 호불호 없이 즐길 수 있도록 했다. 보통 제육볶음과 돈까스 중 한 가지로 메뉴 구성이 되는 데 반해, 이번 ‘제육돈까스 도련님’은 두가지 메인 요리를 하나의 메뉴에 모두 담은 것은 물론 햄버그스테이크와 입맛 돋우는 샐러드, 그리고 반찬까지 총 7종의 음식들로 푸짐한 한끼 식사를 만들었다. ‘김피탕’은 대표 K-푸드인 ‘김치’에 탕수육과 감자튀김, 트리플 치즈가 함께 어우러져 간식이나 안주로 제격인 메뉴다. 한국인의 입맛을 저격하는 새콤달콤한 볶음김치와 바삭한 칠리 찹쌀탕수육, 케이준 감자튀김을 황금비율로 조화롭게 버무려 맛없을 수가 없는 ‘맛없없 조합’을 연출했다. 그 위에 풍성하게 더해진 트리플 치즈가 고소함을 배가시킨다.',
        icon: 'images/content/news/news_icons.png',
    },
    {
        id: 4,
        link: 'https://segye.com/newsView/20240303507753?OutUrl=naver',
        date: '2024-03-03',
        image: 'images/content/news/04.jpg',
        name: '세계일보',
        title: "한솥, 성시경 '인생 설렁탕' 이남장과 협업 도시락 출시",
        text: "한솥도시락이 설렁탕 전문점인 이남장과 협업해 도시락 '이남장 설렁탕' 신메뉴를 수량 한정으로 선보인다고 3일 밝혔다.이남장 설렁탕은 이남장의 노하우와 비법이 그대로 적용된 상품이다. 이남장은 50년 이상 역사를 자랑하는 설렁탕 전문점으로 서울 3대 설렁탕 중 한 곳으로 불리고 있다. 최근에는 가수 겸 방송인인 성시경 유튜브 채널에서 '인생 설렁탕'으로 소개된 적도 있다.",
        icon: 'images/content/news/news_icons.png',
    },
    {
        id: 5,
        link: 'https://jmagazine.joins.com/forbes/view/339176',
        date: '2024-02-06',
        image: 'images/content/news/05.jpg',
        name: '포브스코리아',
        title: '[2024 소비자 선정 최고의 브랜드 대상] 한솥',
        text: '외식 프랜차이즈 한솥도시락은 1993년 창업 이래 “따끈한 도시락으로 지역사회에 공헌한다”는 기업 이념 아래 한솥 ESG정신(양심, 배려, 정직)을 바탕으로 ESG 경영을 지속적으로 실천하고 있다. 지역 농가와의 상생으로 계약재배를 통한 쌀을 공급하고 있으며 배추부터 소금, 젓갈, 고추가루까지 100% 국내산 김치 사용을 창사 이래 지금까지 고집해 오고 있다. 국내산 돼지고기, 청정지역 호주산 쇠고기 등 식재료에 대한 엄격한 기준을 적용하고 있다. 한솥도시락의 ESG 활동과 친환경 모델은 EU(유럽연합) 본부에서 모범 사례로 꼽혔으며, 애플, 디즈니 등 글로벌 브랜드와 함께 2019년부터 ‘글로벌 지속가능한 브랜드 40’에 5년 연속 선정, 국내 최초로 유일하게 UN 식량 시스템 정상 회의 ‘세계 최우수 식품 중소기업 150’에 선정되기도 했다.',
        icon: 'images/content/news/news_icons.png',
    },
    {
        id: 6,
        link: 'https://segye.com/newsView/20240205503755?OutUrl=naver',
        date: '2024-02-06',
        image: 'images/content/news/06.jpg',
        name: '세계일보',
        title: '한솥도시락, ‘한우 함박스테이크 2종’ 2월 재출시',
        text: '국내 대표 도시락 프랜차이즈 한솥도시락이 지난해 9월 인기 메뉴였던 ‘한우 함박스테이크 2종’을 수량한정으로 재출시했다. ‘한우 함박스테이크’는 한솥의 ‘한우 농가 상생 프로젝트’의 일환으로 지난해 9월 첫 선보인 ESG메뉴다. 출시 이후 소비자들에게 많은 인기를 얻으며 베스트셀러 반열에 올랐다. 한솥도시락은 한우 함박스테이크에 대한 소비자들의 성원에 힘입어 재출시를 결정했다고 밝혔다. 한솥도시락은 한우 함박스테이크 2종의 인기 배경으로 ‘맛과 품질’, 그리고 ’가치소비’를 꼽았다. 먼저 한우 함박스테이크는 고품질의 한우와 국내산 돼지고기를 사용해 육즙 가득한 풍미가 일품이다. 여기에 한솥 특제 데미그라스 소스를 곁들여 스테이크의 감칠맛을 더하며 풍성한 맛을 자랑한다. 다양한 사이드 메뉴와 고객의 선택의 폭을 넓힌 것도 인기 요소 중 하나다. 사이드 메뉴로는 해시포테이토, 고구마 샐러드, 콘 샐러드, 그린빈스 등이 있으며 돈까스 또는 토네이도 소세지 중 하나를 선택할 수 있는 것도 인기 요소다. ‘한우 함박스테이크’에는 한솥도시락의 ESG 경영 가치가 녹아 있다. 한우 농가와의 거래를 통해 고품질의 한우를 안정적으로 구매하며 한우 소비를 촉진하고, 지역 농가와 상생을 이루기 때문이다. 소비자는 ‘한우 함박스테이크’ 구매만으로도 ESG 실천에 기여할 수 있다.',
        icon: 'images/content/news/news_icons.png',
    },
    {
        id: 7,
        link: 'https://daily.hankooki.com/news/articleView.html?idxno=1048274',
        date: '2024-02-02',
        image: 'images/content/news/07.jpg',
        name: '데일리한국',
        title: '한솥도시락, ‘사골 조랭이떡 만둣국’ 출시',
        text: '한솥도시락이 설 명절과 잘 어울리는 ‘사골 조랭이떡 만둣국’을 수량한정으로 출시했다고 2일 밝혔다. 쫄깃한 식감과 풍성한 구성, 깊은 국물의 맛이 조화롭게 어우러지는 것이 특징이다. 쫄깃쫄깃한 식감이 일품인 조랭이떡을 사용해 먹는 즐거움을 더했다. 떡을 씹을수록 깊이 베어 있는 국물이 새어 나와 감칠맛을 느낄 수 있다. 속이 꽉 차고 두툼한 국내산 고기만두 2개와 국내산 김치만두 2개를 맛볼 수 있다. 국물 베이스로는 고온에서 오랜 시간 우려낸 우사골 육수를 사용했다. 진하고 깊은 사골의 맛과 쫄깃한 식감, 풍성한 구성을 갖춘 떡국을 가성비 높은 가격으로 만나볼 수 있다.',
        icon: 'images/content/news/news_icons.png',
    },
    {
        id: 8,
        link: 'https://segye.com/newsView/20240119504139?OutUrl=naver',
        date: '2024-01-19',
        image: 'images/content/news/08.jpg',
        name: '세계일보',
        title: '한솥도시락, ‘착한도시락’으로 2300만원 기부',
        text: '한솥도시락이 지난 12월 진행한 ‘착한도시락’ 기부 행사를 통해 적립된 기부금 2,300만원을 글로벌 아동권리 전문 NGO 굿네이버스에 기부한다고 밝혔다. ‘착한도시락’ 기부 행사는 ESG 경영의 일환으로 지난 2018년부터 매년 연말 진행하고 있는 사회공헌활동이다. 고객이 ‘착한도시락’을 구매하면 한솥도시락에서 도시락 1개당 100원의 기부금을 적립한다. 적립된 금액은 아동을 위한 NGO에 전액 기부된다. 착한도시락은 매년 12월 출시되는 신메뉴를 중심으로 구성된다. 올해는 ‘얼큰 소고기국밥’과 ‘얼큰 해물탕’, ‘햄버그 나폴리탄 스파게티&찬차마요 드립백 커피’ 세트, ‘찬차마요 드립백 커피’ 등 총 4종으로 구성되었다. 한솥도시락이 지난 2018년부터 해마다 12월 한달 동안, 그 해에 출시된 신메뉴 위주로 선정된 착한도시락을 고객이 구입하시면 도시락 1개당 100원씩 본부가 부담해서 기부하는 행사를 실행해왔다. 작년12월까지 누적 기부금액은 총 1억 4,400만원이다. ▲2018년에는 2,186만 1,700원 ▲2019년에는 2,261만 8,100원 ▲2020년 2,000만 원 ▲2021년 3,300만 400원 ▲2022년 2,300만원 ▲2023년에는 2,300만원을 기부해왔다. 매년 전달된 기부금은 저소득층 아이들의 건강한 성장을 돕는 복지사업에 사용된다.',
        icon: 'images/content/news/news_icons.png',
    },
    {
        id: 9,
        link: 'https://www.thefirstmedia.net/news/articleView.html?idxno=136013',
        date: '2024-01-09',
        image: 'images/content/news/09.jpg',
        name: '더퍼스트',
        title: '한솥도시락, ‘페루 찬차마요 드립백 커피’ 할인 행사 진행',
        text: '한솥도시락은 ‘페루 찬차마요 드립백 커피’ 할인 행사를 진행한다고 8일 밝혔다. 이번 할인 행사는 전국 한솥도시락 매장과 배달앱 배달의민족에서 동시에 진행되며, 모든 도시락 구매 시 정상가 대비 510원 할인된 가격에 만나볼 수 있다. 도시락 1개당 페루 찬차마요 드립백 커피가 1개씩 할인된다. 한솥 ‘페루 찬차마요 드립백 커피’에 사용되는 커피는 해발 1,500m 이상의 고산지대에서 무농약·무비료로 재배된 남미 최고급 스페셜티 그레이드의 핸드피킹 싱글 오리진 커피다. 깊고 풍부한 향과 단맛과 쓴맛, 신맛이 조화롭게 어우러지면서 높은 품격을 만끽할 수 있다. 한솥도시락은 ESG경영의 일환으로 지난 2012년 처음으로 찬차마요 커피를 선보인 이후 지속적으로 찬차마요 산지와 직거래를 통해 페루 농민들을 후원하고 있다. 한솥도시락 관계자는 “보다 많은 고객분들이 든든한 식사와 향과 맛이 좋은 ’페루 찬차마요 드립백 커피’를 함께 즐길 수 있도록 이번 할인 행사를 진행하게 되었다”며 “’페루 찬차마요 드립백 커피’ 처럼 공정무역을 통해 지역 농가와 상생을 실천하며 좋은 품질의 메뉴를 합리적인 가격으로 선보일 수 있도록 더욱 노력하겠다”고 전했다.',
        icon: 'images/content/news/news_icons.png',
    },
];

//  //.hansot
